# https://docs.docker.com/compose/compose-file/
version: '3'
services:
  local-mongo:
    image: mongo:3.7.9
    ports:
      - "27017:27017"
  local-openid:
    build:
      context: .
      dockerfile: local-openid.docker
    image: local-openid
    volumes:
      - ./.local-openid/:/root/.local-openid
    ports:
      - "4567:4567"   #=> OpenId Provider Url will be http://localhost:4567/
